"""增加收藏文章的关联表

Revision ID: bfb970f01cbf
Revises: e202ebefff8a
Create Date: 2018-08-16 20:40:12.715728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb970f01cbf'
down_revision = 'e202ebefff8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_column('posts', 'love')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('love', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('collect')
    # ### end Alembic commands ###
