"""删除评论回复关联表,改评论回复模式

Revision ID: debb1fdf2524
Revises: bfb970f01cbf
Create Date: 2018-08-20 22:19:53.268829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'debb1fdf2524'
down_revision = 'bfb970f01cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replys')
    op.add_column('comment', sa.Column('ost_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('target_username', sa.String(length=64), nullable=True))
    op.drop_constraint('comment_post_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'posts', ['ost_id'], ['id'])
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_post_id_fkey', 'comment', 'posts', ['post_id'], ['id'])
    op.drop_column('comment', 'target_username')
    op.drop_column('comment', 'ost_id')
    op.create_table('replys',
    sa.Column('replying_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('replyed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['replyed_id'], ['comment.id'], name='replys_replyed_id_fkey'),
    sa.ForeignKeyConstraint(['replying_id'], ['comment.id'], name='replys_replying_id_fkey'),
    sa.PrimaryKeyConstraint('replying_id', 'replyed_id', name='replys_pkey')
    )
    # ### end Alembic commands ###
