"""增加评论点赞字段

Revision ID: e952f9b0fbf4
Revises: debb1fdf2524
Create Date: 2018-08-20 23:48:03.477696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e952f9b0fbf4'
down_revision = 'debb1fdf2524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('like', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_target_username'), 'comment', ['target_username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_target_username'), table_name='comment')
    op.drop_column('comment', 'like')
    # ### end Alembic commands ###
